import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import WalletAdapter from "@/components/layouts/WalletAdapter";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/next.svg",
    },
    openGraph: {
        title: "Create Next App",
        description: "Generated by create next app",
        type: "website",
        locale: "en_US",
        images: [
            // {
            //     url: image ? image.url : '/og-image.jpg',
            //     width: image.width ? image.width : 1200,
            //     height: image.height ? image.height : 630,
            //     alt: title,
            // }
        ],
        siteName: "CreateNextApp",
    },
    twitter: {
        card: "summary_large_image",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin=""
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
                    rel="stylesheet"
                />
            </head>
            <WalletAdapter>
                <body>
                    <Header />
                    <div
                        style={{
                            minHeight: "calc(100vh - 330px)",
                        }}
                    >
                        {children}
                    </div>
                    <Footer />
                </body>
            </WalletAdapter>
        </html>
    );
}
